export const registry = {
  button: {
    name: "button",
    type: "components:ui",
    files: ["src/components/button.tsx"],
    dependencies: ["class-variance-authority", "clsx", "tailwind-merge"],
    registryDependencies: [],
  },
  // Atomic
  "answer": {
    name: "answer",
    type: "components:ui",
    files: ["src/components/legali/atomic/Answer.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: [],
  },
  "glass-card": {
    name: "glass-card",
    type: "components:ui",
    files: ["src/components/legali/atomic/GlassCard.tsx"],
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
  },
  "lesson-dot": {
    name: "lesson-dot",
    type: "components:ui",
    files: ["src/components/legali/atomic/LessonDot.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: [],
  },
  "progress-bar": {
    name: "progress-bar",
    type: "components:ui",
    files: ["src/components/legali/atomic/ProgressBar.tsx"],
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [],
  },
  "stat-item": {
    name: "stat-item",
    type: "components:ui",
    files: ["src/components/legali/atomic/StatItem.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: [],
  },
  "stat-row": {
    name: "stat-row",
    type: "components:ui",
    files: ["src/components/legali/atomic/StatRow.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: [],
  },
  "status-bar": {
    name: "status-bar",
    type: "components:ui",
    files: ["src/components/legali/atomic/StatusBar.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: [],
  },
  // Composite
  "module-card": {
    name: "module-card",
    type: "components:ui",
    files: ["src/components/legali/composite/ModuleCard.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: ["progress-bar", "lesson-dot", "glass-card"],
  },
  "navigation-bar": {
    name: "navigation-bar",
    type: "components:ui",
    files: ["src/components/legali/composite/NavigationBar.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: [],
  },
  "progress-section": {
    name: "progress-section",
    type: "components:ui",
    files: ["src/components/legali/composite/ProgressSection.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: ["progress-bar"],
  },
  "quiz-feedback": {
    name: "quiz-feedback",
    type: "components:ui",
    files: ["src/components/legali/composite/QuizFeedback.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: ["button"],
  },
  "quiz-header": {
    name: "quiz-header",
    type: "components:ui",
    files: ["src/components/legali/composite/QuizHeader.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: ["progress-bar"],
  },
  "quiz-question": {
    name: "quiz-question",
    type: "components:ui",
    files: ["src/components/legali/composite/QuizQuestion.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: [],
  },
  "results-card": {
    name: "results-card",
    type: "components:ui",
    files: ["src/components/legali/composite/ResultsCard.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: ["button", "stat-row"],
  },
  "user-stats-bar": {
    name: "user-stats-bar",
    type: "components:ui",
    files: ["src/components/legali/composite/UserStatsBar.tsx"],
    dependencies: ["lucide-react", "clsx", "tailwind-merge"],
    registryDependencies: ["stat-item"],
  },
};

export type RegistryEntry = typeof registry[keyof typeof registry];
